extends: seegno

ecmaFeatures:
  jsx: true

env:
  browser: true

plugins:
  react

rules:
  complexity: 0
  id-length: [2, { "exceptions": ["e", "_"]}]
  jsx-quotes: 2
  no-extra-parens: 0
  react/display-name: 0
  react/jsx-boolean-value: 2
  react/jsx-closing-bracket-location: 2
  react/jsx-curly-spacing: 2
  react/jsx-indent-props: [1, 2]
  react/jsx-max-props-per-line: 2
  react/jsx-no-bind: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-no-literals: 2
  react/jsx-no-undef: 2
  react/jsx-sort-prop-types: 2
  react/jsx-sort-props: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2
  react/no-danger: 2
  react/no-did-mount-set-state: 2
  react/no-did-update-set-state: 2
  react/no-direct-mutation-state: 2
  react/no-multi-comp: 2
  react/no-unknown-property: 2
  react/prefer-es6-class: 2
  react/prop-types: 2
  react/react-in-jsx-scope: 2
  react/require-extension: 2
  react/self-closing-comp: 2
  react/wrap-multilines: 2

  # Babel plugin
  babel/arrow-parens: 0
  babel/generator-star-spacing: 0
